---
name: chef-cookbook-test-kitchen

on:
  workflow_call:
    secrets:
      TK_AWS_ACCESS_KEY:
        description: 'The AWS CLI Access Key'
        required: true
      TK_AWS_SECRET_ACCESS_KEY:
        description: 'The AWS CLI Secret Access Key'
        required: true
      TK_AWS_SSH_PRIVATE_KEY:
        description: 'The AWS SSH private KEY to be used (optional)'
        required: false
      TK_AWS_SSH_KEY_ID:
        description: 'The SSH public KEY ID within AWS (optional)'
        required: false
      TK_AWS_SUBNET_ID:
        description: 'AWS Subnet ID where to start EC2 instances'
        required: true
      TK_AWS_SG_ID:
        description: 'Security Group to ue'
        required: true
      TK_AWS_INTERFACE:
        description: 'Should be always public'
        required: false
      TK_AWS_ASSOCIATE_PUBLIC_IP:
        description: 'Should a public IP automatically assigned to the EC2 instances'
        required: false
      TK_AWS_REGION:
        description: 'The AWS Region where to start EC2 instances'
        required: false

jobs:
  dokken:
    runs-on: ubuntu-latest
    if: contains( github.event.repository.topics, 'chef-cookbook' ) && contains( github.event.repository.topics, 'opensource' )
    strategy:
      matrix:
        os: ['amazon2', 'centos-7', 'centos-8', 'debian-9', 'debian-10', 'opensuse-leap-15', 'ubuntu-1604', 'ubuntu-1804', 'ubuntu-2004']
        suite: ['default']
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Run test-kitchen
        run: |
          kitchen test ${SUITE}-${OS} -d always
        env:
          SUITE: ${{matrix.suite}}
          OS: ${{matrix.os}}
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
  internal-aws:
    runs-on: ubuntu-latest
    if: contains( github.event.repository.topics, 'chef-cookbook' ) && contains( github.event.repository.topics, 'internal' )
    strategy:
      matrix:
        os: ['amazon', 'amazon2', 'ubuntu-1604', 'ubuntu-1804', 'ubuntu-2004', 'centos-7', 'rhel-77', 'rhel-8']
        suite: ['default']
      fail-fast: false
    steps:
    - name: Check out code
      uses: actions/checkout@main
    - name: Install Chef
      uses: actionshub/chef-install@main
    - name: Configure aws cli
      run: |
        mkdir ~/.aws
        chmod 700 ~/.aws
        echo "[default]" > ~/.aws/config
        echo "output=json" >> ~/.aws/config
        chmod 600 ~/.aws/config
        echo "[default]" >> ~/.aws/credentials
        echo "aws_access_key_id=${TK_AWS_ACCESS_KEY}" >> ~/.aws/credentials
        echo "aws_secret_access_key=${TK_AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials
        chmod 600 ~/.aws/credentials
      env:
        TK_AWS_ACCESS_KEY: ${{ secrets.TK_AWS_ACCESS_KEY }}
        TK_AWS_SECRET_ACCESS_KEY: ${{ secrets.TK_AWS_SECRET_ACCESS_KEY }}
    - name: Configure SSH
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        echo "${TK_AWS_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa-kitchen
        chmod 600 ~/.ssh/id_rsa-kitchen
      env:
        TK_AWS_SSH_PRIVATE_KEY: ${{ secrets.TK_AWS_SSH_PRIVATE_KEY }}
    - name: Run test-kitchen
      run: |
        kitchen test ${SUITE}-${OS} -d always
      env:
        SUITE: ${{matrix.suite}}
        OS: ${{matrix.os}}
        CHEF_LICENSE: accept-no-persist
        KITCHEN_LOCAL_YAML: kitchen.ec2.yml
        TK_AWS_SSH_KEY_ID: ${{secrets.TK_AWS_SSH_KEY_ID}}
        TK_AWS_SUBNET_ID: ${{secrets.TK_AWS_SUBNET_ID}}
        TK_AWS_SG_ID: ${{secrets.TK_AWS_SG_ID}}
        TK_AWS_INTERFACE: ${{secrets.TK_AWS_INTERFACE}}
        TK_AWS_ASSOCIATE_PUBLIC_IP: ${{secrets.TK_AWS_ASSOCIATE_PUBLIC_IP}}
        TK_AWS_REGION: ${{secrets.TK_AWS_REGION}}
